CREATE TABLE USERS (
	ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AUTH0_ID VARCHAR(30) NOT NULL
    
);
CREATE TABLE PRODUCTS (
	ID VARCHAR(36) PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    PRICE INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE CARTS (
	ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE TABLE CART_ITEM (
	ID VARCHAR(36) PRIMARY KEY,
    CART_ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE PAYMENT_METHODS (
    ID VARCHAR(36) PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL

);
CREATE TABLE ORDERS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    PAYMENT_ID VARCHAR(36) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ORDER_ITEM (
    ID VARCHAR(36) PRIMARY KEY,
    ORDER_ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE INTEGER NOT NULL
);
ALTER TABLE CARTS ADD CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE CART_ITEMS ADD CONSTRAINT FK_CART_ITEM_CART FOREIGN KEY (CART_ID) REFERENCES CARTS(ID);
ALTER TABLE CART_ITEMS ADD CONSTRAINT FK_CART_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID);
ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDER_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT_METHODS(ID);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);
